[build]
  publish = "public"
  command = "npm install"

[context.production.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  command = "npm start"
  port = 3000
  publish = "public"
