[build]
  publish = "build"
  command = "npm run build"

[context.production.environment]
  REACT_APP_API_URL = "https://crm-backend-api.example.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
