[build]
  command = "cd frontend && npm install && npm run build && cd ../backend/functions && npm install"
  publish = "frontend/build"
  functions = "backend/functions"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"
  external_node_modules = ["sqlite3", "pg-hstore", "sequelize"]
  included_files = ["backend/functions/config/database.js"]

[dev]
  command = "cd frontend && npm start"
  port = 3000
  publish = "frontend/build"
  functions = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
