# Ultra-simplified Netlify configuration for CRM deployment
[build]
  base = "/"
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "backend/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sqlite3", "pg-hstore", "sequelize"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
