[build]
  command = "cd frontend && npm install && cd ../backend/functions && npm install"
  publish = "frontend/netlify"
  functions = "backend/functions"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"
  external_node_modules = ["sqlite3"]

[dev]
  command = "cd frontend && npm start"
  port = 3000
  publish = "frontend/netlify"
  functions = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
